"""empty message

Revision ID: 82ed8047e2be
Revises: 6063dd6c03ee
Create Date: 2025-12-12 21:45:00.228165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82ed8047e2be'
down_revision = '6063dd6c03ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_commissions_financial_transaction_id', table_name='commissions')
    op.alter_column('companies', 'cnpj',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=18),
               existing_nullable=True)
    op.drop_index('ix_company_subscriptions_plan_type', table_name='company_subscriptions')
    op.create_index(op.f('ix_company_subscriptions_id'), 'company_subscriptions', ['id'], unique=False)
    op.drop_index('ix_company_users_invited_by_id', table_name='company_users')
    op.create_index(op.f('ix_company_users_id'), 'company_users', ['id'], unique=False)
    op.drop_index('ix_financial_transactions_invoice_id', table_name='financial_transactions')
    op.drop_index('ix_financial_transactions_payment_id', table_name='financial_transactions')
    op.drop_index('ix_financial_transactions_professional_id', table_name='financial_transactions')
    op.drop_index('ix_financial_transactions_subscription_sale_id', table_name='financial_transactions')
    op.create_index(op.f('ix_financial_transactions_is_paid'), 'financial_transactions', ['is_paid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_transactions_is_paid'), table_name='financial_transactions')
    op.create_index('ix_financial_transactions_subscription_sale_id', 'financial_transactions', ['subscription_sale_id'], unique=False)
    op.create_index('ix_financial_transactions_professional_id', 'financial_transactions', ['professional_id'], unique=False)
    op.create_index('ix_financial_transactions_payment_id', 'financial_transactions', ['payment_id'], unique=False)
    op.create_index('ix_financial_transactions_invoice_id', 'financial_transactions', ['invoice_id'], unique=False)
    op.drop_index(op.f('ix_company_users_id'), table_name='company_users')
    op.create_index('ix_company_users_invited_by_id', 'company_users', ['invited_by_id'], unique=False)
    op.drop_index(op.f('ix_company_subscriptions_id'), table_name='company_subscriptions')
    op.create_index('ix_company_subscriptions_plan_type', 'company_subscriptions', ['plan_type'], unique=False)
    op.alter_column('companies', 'cnpj',
               existing_type=sa.String(length=18),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.create_index('ix_commissions_financial_transaction_id', 'commissions', ['financial_transaction_id'], unique=False)
    # ### end Alembic commands ###

