"""add_online_booking_configuration_tables

Revision ID: c58a084b3a2d
Revises: add_icons_to_addons
Create Date: 2025-12-31 22:19:49.984300

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c58a084b3a2d'
down_revision = 'add_icons_to_addons'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('global_settings')
    op.drop_index('idx_audit_logs_action', table_name='audit_logs')
    op.drop_index('idx_audit_logs_actor', table_name='audit_logs')
    op.drop_index('idx_audit_logs_created', table_name='audit_logs')
    op.drop_index('idx_audit_logs_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.alter_column('add_ons', 'color',
               existing_type=sa.VARCHAR(length=7),
               nullable=True,
               existing_server_default=sa.text("'#3B82F6'::character varying"))
    op.drop_constraint('add_ons_name_key', 'add_ons', type_='unique')
    op.drop_constraint('add_ons_slug_key', 'add_ons', type_='unique')
    op.drop_index('ix_add_ons_category', table_name='add_ons')
    op.drop_index('ix_add_ons_name', table_name='add_ons')
    op.create_index(op.f('ix_add_ons_name'), 'add_ons', ['name'], unique=True)
    op.drop_index('ix_add_ons_slug', table_name='add_ons')
    op.create_index(op.f('ix_add_ons_slug'), 'add_ons', ['slug'], unique=True)
    op.create_index(op.f('ix_add_ons_id'), 'add_ons', ['id'], unique=False)
    op.drop_column('companies', 'active_addons')
    op.create_index(op.f('ix_company_add_ons_id'), 'company_add_ons', ['id'], unique=False)
    op.drop_constraint('fk_company_subscriptions_plan_id', 'company_subscriptions', type_='foreignkey')
    op.drop_column('company_subscriptions', 'plan_id')
    op.drop_column('company_subscriptions', 'auto_renew')
    op.drop_column('company_subscriptions', 'next_billing_date')
    op.drop_column('company_subscriptions', 'billing_cycle')
    op.drop_index('ix_plans_company_id', table_name='package_plans')
    op.drop_index('ix_plans_id', table_name='package_plans')
    op.create_index(op.f('ix_package_plans_company_id'), 'package_plans', ['company_id'], unique=False)
    op.create_index(op.f('ix_package_plans_id'), 'package_plans', ['id'], unique=False)
    op.alter_column('plans', 'color',
               existing_type=sa.VARCHAR(length=7),
               nullable=True,
               existing_server_default=sa.text("'#3B82F6'::character varying"))
    op.drop_constraint('plans_name_key', 'plans', type_='unique')
    op.drop_constraint('plans_slug_key', 'plans', type_='unique')
    op.drop_index('ix_plans_name', table_name='plans')
    op.create_index(op.f('ix_plans_name'), 'plans', ['name'], unique=True)
    op.drop_index('ix_plans_slug', table_name='plans')
    op.create_index(op.f('ix_plans_slug'), 'plans', ['slug'], unique=True)
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.add_column('services', sa.Column('available_online', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'available_online')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_slug'), table_name='plans')
    op.create_index('ix_plans_slug', 'plans', ['slug'], unique=False)
    op.drop_index(op.f('ix_plans_name'), table_name='plans')
    op.create_index('ix_plans_name', 'plans', ['name'], unique=False)
    op.create_unique_constraint('plans_slug_key', 'plans', ['slug'])
    op.create_unique_constraint('plans_name_key', 'plans', ['name'])
    op.alter_column('plans', 'color',
               existing_type=sa.VARCHAR(length=7),
               nullable=False,
               existing_server_default=sa.text("'#3B82F6'::character varying"))
    op.drop_index(op.f('ix_package_plans_id'), table_name='package_plans')
    op.drop_index(op.f('ix_package_plans_company_id'), table_name='package_plans')
    op.create_index('ix_plans_id', 'package_plans', ['id'], unique=False)
    op.create_index('ix_plans_company_id', 'package_plans', ['company_id'], unique=False)
    op.add_column('company_subscriptions', sa.Column('billing_cycle', sa.VARCHAR(length=20), server_default=sa.text("'monthly'::character varying"), autoincrement=False, nullable=True))
    op.add_column('company_subscriptions', sa.Column('next_billing_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('company_subscriptions', sa.Column('auto_renew', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('company_subscriptions', sa.Column('plan_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_company_subscriptions_plan_id', 'company_subscriptions', 'plans', ['plan_id'], ['id'])
    op.drop_index(op.f('ix_company_add_ons_id'), table_name='company_add_ons')
    op.add_column('companies', sa.Column('active_addons', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_add_ons_id'), table_name='add_ons')
    op.drop_index(op.f('ix_add_ons_slug'), table_name='add_ons')
    op.create_index('ix_add_ons_slug', 'add_ons', ['slug'], unique=False)
    op.drop_index(op.f('ix_add_ons_name'), table_name='add_ons')
    op.create_index('ix_add_ons_name', 'add_ons', ['name'], unique=False)
    op.create_index('ix_add_ons_category', 'add_ons', ['category'], unique=False)
    op.create_unique_constraint('add_ons_slug_key', 'add_ons', ['slug'])
    op.create_unique_constraint('add_ons_name_key', 'add_ons', ['name'])
    op.alter_column('add_ons', 'color',
               existing_type=sa.VARCHAR(length=7),
               nullable=False,
               existing_server_default=sa.text("'#3B82F6'::character varying"))
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('actor_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('actor_role', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name='audit_logs_actor_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='audit_logs_pkey')
    )
    op.create_index('idx_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_logs_created', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_logs_actor', 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index('idx_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_table('global_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint('id = 1', name='single_row_constraint'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='global_settings_updated_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='global_settings_pkey')
    )
    # ### end Alembic commands ###

