"""Complete DB schema

Revision ID: f9657ff9a0d5
Revises: 3defd0baf6a1
Create Date: 2026-01-07 02:07:16.730444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9657ff9a0d5'
down_revision = '3defd0baf6a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('online_booking_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'online_booking_enabled')
    # ### end Alembic commands ###

